sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t xhlasn/doker-react -f Dockerfile.dev .
script:
  #- docker run xhlasn/docker-react npm run test -- --coverage
  - docker run -e CI=true xhlasn/docker-react npm run test

