sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t xhlasn/docker-react -f Dockerfile.dev .
script:
  #- docker run xhlasn/docker-react npm run test -- --coverage
  - docker run -e CI=true xhlasn/docker-react npm run test

deploy: # Amazon AWS elastic bean deployemnt
  edge: true
  provider: elasticbeanstalk
  region: 'ap-southeast-2'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-970835374499'
  bucket_path: 'docker-react' # Same as app name, AWS creates a folder after first deployment
  on:
    branch: master # Only deploy, when the code is changed in the master branch
  
  # AWS access keys - defined in travis CI settings
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY